// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'system_env_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$SystemEnvResponseImpl _$$SystemEnvResponseImplFromJson(
  Map<String, dynamic> json,
) => _$SystemEnvResponseImpl(
  success: json['success'] as bool,
  message: _stringFromJson(json['message']),
  data: json['data'] == null
      ? null
      : SystemEnvData.fromJson(json['data'] as Map<String, dynamic>),
);

_$SystemEnvDataImpl _$$SystemEnvDataImplFromJson(
  Map<String, dynamic> json,
) => _$SystemEnvDataImpl(
  configDir: _stringFromJson(json['CONFIG_DIR']),
  debug: _boolFromJson(json['DEBUG']),
  logLevel: _stringFromJson(json['LOG_LEVEL']),
  logMaxFileSize: _intFromJson(json['LOG_MAX_FILE_SIZE']),
  logBackupCount: _intFromJson(json['LOG_BACKUP_COUNT']),
  logConsoleFormat: _stringFromJson(json['LOG_CONSOLE_FORMAT']),
  logFileFormat: _stringFromJson(json['LOG_FILE_FORMAT']),
  asyncFileQueueSize: _intFromJson(json['ASYNC_FILE_QUEUE_SIZE']),
  asyncFileWorkers: _intFromJson(json['ASYNC_FILE_WORKERS']),
  batchWriteSize: _intFromJson(json['BATCH_WRITE_SIZE']),
  writeTimeout: _doubleFromJson(json['WRITE_TIMEOUT']),
  projectName: _stringFromJson(json['PROJECT_NAME']),
  appDomain: _stringFromJson(json['APP_DOMAIN']),
  apiV1Str: _stringFromJson(json['API_V1_STR']),
  frontendPath: _stringFromJson(json['FRONTEND_PATH']),
  tz: _stringFromJson(json['TZ']),
  host: _stringFromJson(json['HOST']),
  port: _intFromJson(json['PORT']),
  nginxPort: _intFromJson(json['NGINX_PORT']),
  dev: _boolFromJson(json['DEV']),
  advancedMode: _boolFromJson(json['ADVANCED_MODE']),
  allowedHosts: _stringListFromJson(json['ALLOWED_HOSTS']),
  accessTokenExpireMinutes: _intFromJson(json['ACCESS_TOKEN_EXPIRE_MINUTES']),
  resourceAccessTokenExpireSeconds: _intFromJson(
    json['RESOURCE_ACCESS_TOKEN_EXPIRE_SECONDS'],
  ),
  superuser: _stringFromJson(json['SUPERUSER']),
  superuserPassword: _stringFromJson(json['SUPERUSER_PASSWORD']),
  auxiliaryAuthEnable: _boolFromJson(json['AUXILIARY_AUTH_ENABLE']),
  apiToken: _stringFromJson(json['API_TOKEN']),
  authSite: _stringFromJson(json['AUTH_SITE']),
  dbType: _stringFromJson(json['DB_TYPE']),
  dbEcho: _boolFromJson(json['DB_ECHO']),
  dbTimeout: _intFromJson(json['DB_TIMEOUT']),
  dbWalEnable: _boolFromJson(json['DB_WAL_ENABLE']),
  dbPoolType: _stringFromJson(json['DB_POOL_TYPE']),
  dbPoolPrePing: _boolFromJson(json['DB_POOL_PRE_PING']),
  dbPoolRecycle: _intFromJson(json['DB_POOL_RECYCLE']),
  dbPoolTimeout: _intFromJson(json['DB_POOL_TIMEOUT']),
  dbSqlitePoolSize: _intFromJson(json['DB_SQLITE_POOL_SIZE']),
  dbSqliteMaxOverflow: _intFromJson(json['DB_SQLITE_MAX_OVERFLOW']),
  dbPostgresqlHost: _stringFromJson(json['DB_POSTGRESQL_HOST']),
  dbPostgresqlPort: _intFromJson(json['DB_POSTGRESQL_PORT']),
  dbPostgresqlDatabase: _stringFromJson(json['DB_POSTGRESQL_DATABASE']),
  dbPostgresqlUsername: _stringFromJson(json['DB_POSTGRESQL_USERNAME']),
  dbPostgresqlPassword: _stringFromJson(json['DB_POSTGRESQL_PASSWORD']),
  dbPostgresqlPoolSize: _intFromJson(json['DB_POSTGRESQL_POOL_SIZE']),
  dbPostgresqlMaxOverflow: _intFromJson(json['DB_POSTGRESQL_MAX_OVERFLOW']),
  cacheBackendType: _stringFromJson(json['CACHE_BACKEND_TYPE']),
  cacheBackendUrl: _stringFromJson(json['CACHE_BACKEND_URL']),
  cacheRedisMaxmemory: _intFromJson(json['CACHE_REDIS_MAXMEMORY']),
  globalImageCache: _boolFromJson(json['GLOBAL_IMAGE_CACHE']),
  globalImageCacheDays: _intFromJson(json['GLOBAL_IMAGE_CACHE_DAYS']),
  tempFileDays: _intFromJson(json['TEMP_FILE_DAYS']),
  metaCacheExpire: _intFromJson(json['META_CACHE_EXPIRE']),
  proxyHost: _stringFromJson(json['PROXY_HOST']),
  dohEnable: _boolFromJson(json['DOH_ENABLE']),
  dohDomains: _stringFromJson(json['DOH_DOMAINS']),
  dohResolvers: _stringFromJson(json['DOH_RESOLVERS']),
  searchSource: _stringFromJson(json['SEARCH_SOURCE']),
  recognizeSource: _stringFromJson(json['RECOGNIZE_SOURCE']),
  scrapSource: _stringFromJson(json['SCRAP_SOURCE']),
  animeGenreIds: _intListFromJson(json['ANIME_GENREIDS']),
  tmdbImageDomain: _stringFromJson(json['TMDB_IMAGE_DOMAIN']),
  tmdbApiDomain: _stringFromJson(json['TMDB_API_DOMAIN']),
  tmdbLocale: _stringFromJson(json['TMDB_LOCALE']),
  tmdbScrapOriginalImage: _boolFromJson(json['TMDB_SCRAP_ORIGINAL_IMAGE']),
  tmdbApiKey: _stringFromJson(json['TMDB_API_KEY']),
  tvdbV4ApiKey: _stringFromJson(json['TVDB_V4_API_KEY']),
  tvdbV4ApiPin: _stringFromJson(json['TVDB_V4_API_PIN']),
  fanartEnable: _boolFromJson(json['FANART_ENABLE']),
  fanartLang: _stringFromJson(json['FANART_LANG']),
  fanartApiKey: _stringFromJson(json['FANART_API_KEY']),
  u115AppId: _stringFromJson(json['U115_APP_ID']),
  u115AuthServer: _stringFromJson(json['U115_AUTH_SERVER']),
  alipanAppId: _stringFromJson(json['ALIPAN_APP_ID']),
  moviepilotAutoUpdate: _stringFromJson(json['MOVIEPILOT_AUTO_UPDATE']),
  autoUpdateResource: _boolFromJson(json['AUTO_UPDATE_RESOURCE']),
  rmtMediaext: _stringListFromJson(json['RMT_MEDIAEXT']),
  rmtSubext: _stringListFromJson(json['RMT_SUBEXT']),
  rmtAudioext: _stringListFromJson(json['RMT_AUDIOEXT']),
  mediaserverSyncInterval: _intFromJson(json['MEDIASERVER_SYNC_INTERVAL']),
  subscribeMode: _stringFromJson(json['SUBSCRIBE_MODE']),
  subscribeRssInterval: _intFromJson(json['SUBSCRIBE_RSS_INTERVAL']),
  subscribeStatisticShare: _boolFromJson(json['SUBSCRIBE_STATISTIC_SHARE']),
  subscribeSearch: _boolFromJson(json['SUBSCRIBE_SEARCH']),
  subscribeSearchInterval: _intFromJson(json['SUBSCRIBE_SEARCH_INTERVAL']),
  localExistsSearch: _boolFromJson(json['LOCAL_EXISTS_SEARCH']),
  sitedataRefreshInterval: _intFromJson(json['SITEDATA_REFRESH_INTERVAL']),
  siteMessage: _boolFromJson(json['SITE_MESSAGE']),
  noCacheSiteKey: _stringFromJson(json['NO_CACHE_SITE_KEY']),
  ocrHost: _stringFromJson(json['OCR_HOST']),
  browserEmulation: _stringFromJson(json['BROWSER_EMULATION']),
  flaresolverrUrl: _stringFromJson(json['FLARESOLVERR_URL']),
  searchMultipleName: _boolFromJson(json['SEARCH_MULTIPLE_NAME']),
  maxSearchNameLimit: _intFromJson(json['MAX_SEARCH_NAME_LIMIT']),
  torrentTag: _stringFromJson(json['TORRENT_TAG']),
  downloadSubtitle: _boolFromJson(json['DOWNLOAD_SUBTITLE']),
  autoDownloadUser: _stringFromJson(json['AUTO_DOWNLOAD_USER']),
  downloadTmpext: _stringListFromJson(json['DOWNLOAD_TMPEXT']),
  cookiecloudEnableLocal: _boolFromJson(json['COOKIECLOUD_ENABLE_LOCAL']),
  cookiecloudHost: _stringFromJson(json['COOKIECLOUD_HOST']),
  cookiecloudKey: _stringFromJson(json['COOKIECLOUD_KEY']),
  cookiecloudPassword: _stringFromJson(json['COOKIECLOUD_PASSWORD']),
  cookiecloudInterval: _intFromJson(json['COOKIECLOUD_INTERVAL']),
  cookiecloudBlacklist: _stringFromJson(json['COOKIECLOUD_BLACKLIST']),
  transferThreads: _intFromJson(json['TRANSFER_THREADS']),
  movieRenameFormat: _stringFromJson(json['MOVIE_RENAME_FORMAT']),
  tvRenameFormat: _stringFromJson(json['TV_RENAME_FORMAT']),
  renameFormatS0Names: _stringListFromJson(json['RENAME_FORMAT_S0_NAMES']),
  defaultSub: _stringFromJson(json['DEFAULT_SUB']),
  scrapFollowTmdb: _boolFromJson(json['SCRAP_FOLLOW_TMDB']),
  mpServerHost: _stringFromJson(json['MP_SERVER_HOST']),
  wallpaper: _stringFromJson(json['WALLPAPER']),
  customizeWallpaperApiUrl: _stringFromJson(json['CUSTOMIZE_WALLPAPER_API_URL']),
  pluginMarket: _stringFromJson(json['PLUGIN_MARKET']),
  pluginStatisticShare: _boolFromJson(json['PLUGIN_STATISTIC_SHARE']),
  pluginAutoReload: _boolFromJson(json['PLUGIN_AUTO_RELOAD']),
  githubToken: _stringFromJson(json['GITHUB_TOKEN']),
  githubProxy: _stringFromJson(json['GITHUB_PROXY']),
  pipProxy: _stringFromJson(json['PIP_PROXY']),
  repoGithubToken: _stringFromJson(json['REPO_GITHUB_TOKEN']),
  bigMemoryMode: _boolFromJson(json['BIG_MEMORY_MODE']),
  encodingDetectionPerformanceMode: _boolFromJson(
    json['ENCODING_DETECTION_PERFORMANCE_MODE'],
  ),
  encodingDetectionMinConfidence: _doubleFromJson(
    json['ENCODING_DETECTION_MIN_CONFIDENCE'],
  ),
  memoryGcInterval: _intFromJson(json['MEMORY_GC_INTERVAL']),
  securityImageDomains: _stringListFromJson(json['SECURITY_IMAGE_DOMAINS']),
  securityImageSuffixes: _stringListFromJson(json['SECURITY_IMAGE_SUFFIXES']),
  passkeyRequireUv: _boolFromJson(json['PASSKEY_REQUIRE_UV']),
  passkeyAllowRegisterWithoutOtp: _boolFromJson(
    json['PASSKEY_ALLOW_REGISTER_WITHOUT_OTP'],
  ),
  workflowStatisticShare: _boolFromJson(json['WORKFLOW_STATISTIC_SHARE']),
  rcloneSnapshotCheckFolderModtime: _boolFromJson(
    json['RCLONE_SNAPSHOT_CHECK_FOLDER_MODTIME'],
  ),
  openlistSnapshotCheckFolderModtime: _boolFromJson(
    json['OPENLIST_SNAPSHOT_CHECK_FOLDER_MODTIME'],
  ),
  dockerClientApi: _stringFromJson(json['DOCKER_CLIENT_API']),
  playwrightBrowserType: _stringFromJson(json['PLAYWRIGHT_BROWSER_TYPE']),
  aiAgentEnable: _boolFromJson(json['AI_AGENT_ENABLE']),
  aiAgentGlobal: _boolFromJson(json['AI_AGENT_GLOBAL']),
  llmProvider: _stringFromJson(json['LLM_PROVIDER']),
  llmModel: _stringFromJson(json['LLM_MODEL']),
  llmApiKey: _stringFromJson(json['LLM_API_KEY']),
  llmBaseUrl: _stringFromJson(json['LLM_BASE_URL']),
  llmMaxContextTokens: _intFromJson(json['LLM_MAX_CONTEXT_TOKENS']),
  llmTemperature: _doubleFromJson(json['LLM_TEMPERATURE']),
  llmMaxIterations: _intFromJson(json['LLM_MAX_ITERATIONS']),
  llmToolTimeout: _intFromJson(json['LLM_TOOL_TIMEOUT']),
  llmVerbose: _boolFromJson(json['LLM_VERBOSE']),
  llmMaxMemoryMessages: _intFromJson(json['LLM_MAX_MEMORY_MESSAGES']),
  llmMemoryRetentionDays: _intFromJson(json['LLM_MEMORY_RETENTION_DAYS']),
  llmRedisMemoryRetentionDays: _intFromJson(
    json['LLM_REDIS_MEMORY_RETENTION_DAYS'],
  ),
  aiRecommendEnabled: _boolFromJson(json['AI_RECOMMEND_ENABLED']),
  aiRecommendUserPreference: _stringFromJson(json['AI_RECOMMEND_USER_PREFERENCE']),
  tavilyApiKey: json['TAVILY_API_KEY'] as List<dynamic>?,
  aiRecommendMaxItems: _intFromJson(json['AI_RECOMMEND_MAX_ITEMS']),
  version: _stringFromJson(json['VERSION']),
  authVersion: _stringFromJson(json['AUTH_VERSION']),
  indexerVersion: _stringFromJson(json['INDEXER_VERSION']),
  frontendVersion: _stringFromJson(json['FRONTEND_VERSION']),
);
